{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google",
    "module": "webp",
    "version": "1.5.0-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "exportedAars",
      "attributes": {
        "artifactType": "aar"
      },
      "files": [
        {
          "name": "webp-1.5.0-release.aar",
          "url": "webp-1.5.0-release.aar",
          "size": 3503573,
          "sha512": "3a14761bbd221065872d4e6b2dc7bd4a0dd576f48ea290d621ec5941b78e13ab604b6f8b73a133e31aa46f121bdbba849645198f87b4123335b383b3fcd02266",
          "sha256": "4be0a44fbb3318a8042cdf7ce93e9737b738599be0947e84889667f1cc9be442",
          "sha1": "49c44398d7ff0ae6b8060a38ee6ed1d6e0a5d89a",
          "md5": "3fa4286b1e648159024fd28069e464e7"
        }
      ]
    }
  ]
}
