{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google",
    "module": "webp",
    "version": "1.5.0-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "exportedAars",
      "attributes": {
        "artifactType": "aar"
      },
      "files": [
        {
          "name": "webp-1.5.0-release.aar",
          "url": "webp-1.5.0-release.aar",
          "size": 4133485,
          "sha512": "5dbf7ced63beaf5b6123d7ca687e3d3054a4bcaffd43cd35dd0de3e8bb165bec37f9babed8155f25b5363abb35132f7f3d40a2ba349e47c6d89b194dcf535b85",
          "sha256": "a12a89ba5765b7ecd7d86c5a6781cfb41e1744354e6045968b2fb1de857468ea",
          "sha1": "5b058e986736c7cc78883dea8838acecea49427d",
          "md5": "4c221fe4ac0ec8ccd5c4dd3bca6eaf26"
        }
      ]
    }
  ]
}
