{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bramtechs",
    "module": "touch-scroll-physics-c",
    "version": "1.0.0-debug",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "exportedAars",
      "attributes": {
        "artifactType": "aar"
      },
      "files": [
        {
          "name": "touch-scroll-physics-c-1.0.0-debug.aar",
          "url": "touch-scroll-physics-c-1.0.0-debug.aar",
          "size": 21253,
          "sha512": "877e5f6ea6a02c0b1b34c62208ca1e317821e9f83994d5908c4b9d6be0aa1efa4f716bb0aade07b53b892303cb254ed737a35cf8a782d17b2d82d6cf5a2b0af6",
          "sha256": "79debbd52c634e0a7bcd26cc0f4d93e66888fe2c92f369fc604bc912f15f773c",
          "sha1": "93d74969bf3bb1028320b04eb33fa584e36b9d7d",
          "md5": "65407a8bf82ba25f2e64c9fb2a91c840"
        }
      ]
    }
  ]
}
