{
  "formatVersion": "1.1",
  "component": {
    "group": "com.raysan5",
    "module": "raylib",
    "version": "5.6-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "exportedAars",
      "attributes": {
        "artifactType": "aar"
      },
      "files": [
        {
          "name": "raylib-5.6-release.aar",
          "url": "raylib-5.6-release.aar",
          "size": 7980354,
          "sha512": "dea4e013670962a2c6733e25c0d90d986bf6b8858f234a2c766cac5722bf2bf3a99ca7b61c03e78a37d3530f0f88592f54783cf6df089b488723d3c8845c88d5",
          "sha256": "3e749e8ef1f26a281f38f53a65334b7beaf07f8ef81c45643367b877b405aaf3",
          "sha1": "542e6f16afec9063438b21d0d14973be1d150a4b",
          "md5": "0ec2cafd72ad3a804da87f41c40ffd42"
        }
      ]
    }
  ]
}
