{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doomhowl",
    "module": "raylib",
    "version": "5.6-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "exportedAars",
      "attributes": {
        "artifactType": "aar"
      },
      "files": [
        {
          "name": "raylib-5.6-release.aar",
          "url": "raylib-5.6-release.aar",
          "size": 7981956,
          "sha512": "9c0bc93f588a042a0ffd1d7edb8d621af99ad490ae71f3cabdd3f865a5b6bf6afc600dacc217451488cbde29162425d295095a5f45faace9a9b4f70b4ef73cdc",
          "sha256": "6b79b88a3ced53a3c09fe83fb5c930ea9883e8a5eec7009a7c8386c12e45464c",
          "sha1": "078aa31dab90207c2080d400fb2b78a878bddb94",
          "md5": "e57764ea5257c9a5e15b399ec5920303"
        }
      ]
    }
  ]
}
