{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doomhowl",
    "module": "raylib",
    "version": "5.6-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "exportedAars",
      "attributes": {
        "artifactType": "aar"
      },
      "files": [
        {
          "name": "raylib-5.6-release.aar",
          "url": "raylib-5.6-release.aar",
          "size": 7981956,
          "sha512": "d127b31c09c7b94e255d422b029df369cf69e8378d900ff9caf10e984d8f50421f84b2cd0043cfd9e485bf16ff2236ce8af8c5cac126039b565c10379fc01a84",
          "sha256": "dd6c229b395cf35a9845a86a9ad31b8a9f9f72b55a3b4f33ca5a8a3e7206975d",
          "sha1": "9b8ade08008069d6ad276fc1cb3af57d0c2a4be7",
          "md5": "55156bedcf78844c961f16c00bf79756"
        }
      ]
    }
  ]
}
