{
  "formatVersion": "1.1",
  "component": {
    "group": "com.walterschell",
    "module": "lua",
    "version": "5.4.5-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "exportedAars",
      "attributes": {
        "artifactType": "aar"
      },
      "files": [
        {
          "name": "lua-5.4.5-release.aar",
          "url": "lua-5.4.5-release.aar",
          "size": 1930811,
          "sha512": "e883252b99bf2a4893862e85b2f4f4792eb1bba20140d375dc9aa2b71306b37a75bf8ebffe28f5dd7097fba589bb68ac62e3c5b3c17fd365862c7013db043701",
          "sha256": "46d8b446c0e550d5ac3cc9539cfeee54037f02a05df63d3c23d9b11c64ecbf4f",
          "sha1": "495cfd14f1a67113f848cba05918a73b7824a9b2",
          "md5": "5d615efdd3c1cac6a92eae43db2f314d"
        }
      ]
    }
  ]
}
